### ISSUE TITLE
Running with Profile

### ISSUE THREAD

**Issue by palmerc** [dankogai/swift-complex#10]
Attempting to look into performance using Profile yields compilation error 

> Integer literal '4294967295' overflows when stored into 'Int'

    /// .hashvalue -- conforms to Hashable
    var hashValue:Int { // take most significant halves and join
        let bits = sizeof(Int) * 4
        let mask = bits == 16 ? 0xffff : 0xffffFFFF // Error on this line
        return (re.hashValue & ~mask) | (im.hashValue >> bits)
    }

**Comment by dankogai** [comment]
It has been addressed in the most recent version as follows:

````swift
    /// .hashValue -- conforms to Hashable
    public var hashValue:Int { // take most significant halves and join
        let bits = sizeof(Int) * 4
        let mask = bits == 16 ? 0xffff : 0xffffFFFF
        return re is Int
            ? ((re.hashValue & mask) << bits) | (im.hashValue & mask) // Complex<Int>
            :  (re.hashValue & ~mask) | (im.hashValue >> bits)        // Complex<RealType>
    }
````
