### ISSUE TITLE
import CoreGraphics

### ISSUE THREAD

**Issue by palmerc** [dankogai/swift-complex#11]
complex.swift uses CGFloat and you might want to import CoreGraphics not just Foundation.

**Comment by dankogai** [comment]
`Foundation` suffices for the use by `Complex`.  I would like to keep import as minimalistic as possible.

**Comment by palmerc** [comment]
Doesn't work for me without it. I get an error on CGFloat. Are you importing it somewhere else?

**Comment by dankogai** [comment]
No. just `Foundation`. 

Remember that you have to `import` whatever you need even if complex.swift `import`s it.  For instance the following code does not work without `import Foundation` or `import Darwin`  The following REPL session illustrate that.  In this case `atan2` is missing.

````
% make repl
xcrun -sdk macosx swiftc -emit-library -emit-module complex/complex.swift complex/exops.swift -module-name Complex
swift -I. -L. -lComplex
Welcome to Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81). Type :help for assistance.
  1> import Complex
  2> Complex(abs: 2.0, arg:atan2(1,1))
repl.swift:2:23: error: use of unresolved identifier 'atan2'
Complex(abs: 2.0, arg:atan2(1,1))
                      ^~~~~

  2> import Foundation
  3> Complex(abs: 2.0, arg:atan2(1,1)) 
$R0: Complex.Complex<Double> = {
  re = 1.4142135623730951
  im = 1.4142135623730949
}
  4>  
````

**Comment by palmerc** [comment]
OK, but you’re referencing CGFloat which is a struct defined in CoreGraphics not in Foundation.

init(_: CGFloat)

cameron.

**Comment by dankogai** [comment]
I replaced `import Foundation` with `import Darwin` and `import CoreGraphics` 

https://github.com/dankogai/swift-complex/commit/f1a314599222e5f47711789d819fa0cbbc6f657b

So you are right -- about iOS (and maybe tvOS)
