### ISSUE TITLE
Float80

### ISSUE THREAD

**Issue by fulldecent** [dankogai/swift-complex#14]
Float80 does not seem to be supported any more.

![screen shot 2016-01-27 at 11 46 13 pm](https://cloud.githubusercontent.com/assets/382183/12635396/ae9feb00-c550-11e5-88ae-5971cb92b17f.png)

**Comment by fulldecent** [comment]
I see this exists on Mac but not iOS

**Comment by dankogai** [comment]
fixed in https://github.com/dankogai/swift-complex/commit/44760ab3cbeb2b74dbe13e1c4405c48cc6e0ba19
