### ISSUE TITLE
Overflow

### ISSUE THREAD

**Issue by fulldecent** [dankogai/swift-complex#15]
The bitmask seems to be "overflowing". This may be a compiler error, but I wanted to show it here because it is stopping me from shipping product tonight.

![screen shot 2016-01-27 at 11 49 34 pm](https://cloud.githubusercontent.com/assets/382183/12635421/fe9a3854-c550-11e5-9de6-27ebaadeaecd.png)

**Comment by fulldecent** [comment]
FYI, if you NEED to ship tonight, here is a solution that makes it compile:

        let mask = bits == 16 ? 0xffff : 0x7fffFFFF

**Comment by dankogai** [comment]
See. https://github.com/dankogai/swift-complex/issues/12
