### ISSUE TITLE
Is this compatible with accelerate DSP?

### ISSUE THREAD

**Issue by gaming-hacker** [dankogai/swift-complex#18]
Anyone successfully used this as split complex array with a vDSP routine?

**Comment by dankogai** [comment]
As of now I have no play to accelerate `Complex` itself but remember `Complex` can use any `FloatingPoint` as its real element.  For instance I've already made `BigRat` and `BigFloat` (https://github.com/dankogai/swift-bignum sorry not much documents yet) so `Complex<BigFloat>` is already a reality.  All you need is accelerated floating point number.

**Comment by gaming-hacker** [comment]
Thanks, I'm on to it.
