### ISSUE TITLE
Numerical stability

### ISSUE THREAD

**Issue by asmeurer** [dankogai/swift-complex#3]
Some of the algorithms here are implemented naively, and have numerical stability issues. `/` is one example. There are likely others. 

Take a look at how Python implements complex numbers: http://hg.python.org/cpython/file/3d45155b7b9b/Objects/complexobject.c. Most of those algorithms should be much more stable, numerically.  I'm sure there are other good resources as well.

**Comment by dankogai** [comment]
Since https://github.com/dankogai/swift-complex/commit/8a268f588f72fc07fcb7e7e468da265407c1d0df it is as simple as:
````swift
public func / <T>(lhs:Complex<T>, rhs:Complex<T>) -> Complex<T> {
    return (lhs * rhs.conj) / rhs.norm
}
````
The only division involved is the last `norm`, which is `RealType` so less prone to error and faster.
