### ISSUE TITLE
function pow(lhs: Complex<T> , rhs: T) fails

### ISSUE THREAD

**Issue by matthieudelaro** [dankogai/swift-complex#8]
Hi,

In case lhs == 0, this function will return NaN since it calls another version of pow, which himself calls log(lhs), while log(0) is undefined : 
Complex.swift : line 315 : 
```Swift
func pow<T>(lhs:Complex<T>, rhs:T) -> Complex<T> {
    return pow(lhs, Complex(rhs, T(0))) // calls pow defined line 311
}
```
and line 311 : 
```Swift
func pow<T>(lhs:Complex<T>, rhs:Complex<T>) -> Complex<T> {
    let z = log(lhs) * rhs
    return exp(z)
}
```

So here is my version of this function (I use a template free version of your code since I just need Complex<Double> and since Swift compiler takes so long to compile with templates)) :
```Swift
func pow(lhs:Complex, rhs:Double) -> Complex {
    //return pow(lhs, Complex(rhs, Double(0)))
    return Complex(abs: pow(lhs.norm, rhs), arg: lhs.arg * rhs)
}
```

Anyway thanks for sharing your code, it's pretty handy !

**Comment by dankogai** [comment]
Fixed in https://github.com/dankogai/swift-complex/commit/b362f4af099b26eeb2fe0fe5050a92aeac391c61 . Less Complex solution as follows:

```swift
func pow<T>(lhs:Complex<T>, rhs:Complex<T>) -> Complex<T> {
    if lhs.abs == T(0) { return Complex(T(1), T(0)) } // fix issue 8
    let z = log(lhs) * rhs
    return exp(z)
}
```
